name: Generate Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'git-inject.adoc'
      - 'gen'
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Asciidoctor
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoctor ruby-asciidoctor-pdf

      - name: Run gen script
        run: |
          bash ./gen

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit and Push changes
        run: |
          git config --global user.name "cbsggl-bot"
          git config --global user.email "cbsggl-bot@clitson.nl"
          git add git-inject.1 git-inject.html

          if ! git diff --cached --quiet; then
            git commit -S -m "docs: auto-generate documentation"
            git push origin HEAD
          else
            echo "No changes to commit"
          fi

      - name: Get latest doc tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git tag | grep -E "^doc-[0-9]{4}[0-9]{2}[0-9]{2}$" | sort -t '-' -k 2 -n | tail -n 1)
          if [ -z "$LATEST_TAG" ]; then
            printf "error: unable to locate latest tag"
            exit 1
          fi

          # Get the commit hash for the tag
          TARGET_COMMITISH=$(git rev-parse "$LATEST_TAG")

          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "TARGET_COMMITISH=$TARGET_COMMITISH" >> $GITHUB_ENV

      - name: Create PDF Manual Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.LATEST_TAG }}
          name: PDF Manual (${{ env.LATEST_TAG }})
          target_commitish: ${{ env.TARGET_COMMITISH }}
          body: |
            PDF Manual for git-inject.

            View the HTML documentation [here](https://cdn.clitson.nl/git-inject/docs).
          files: |
            git-inject.pdf
          draft: false
          prerelease: false
          make_latest: false
